### ISSUE TITLE
RelatedObjectDoesNotExist: User has no student.

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#682] opened 2019-05-10 09:31 UTC
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/258/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/258/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1556541473/zapisy/apps/enrollment/timetable/views.py", line 122, in my_timetable
    data = student_timetable_data(request.user.student)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/utils/functional.py", line 214, in inner
    return func(self._wrapped, *args)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 414, in __get__
    self.related.get_accessor_name()
RelatedObjectDoesNotExist: User has no student.
```

**Comment by jasiekmarc** [comment] 2019-05-10 09:45
Duplicate of #681.

**Closed by jasiekmarc** 2019-05-10 09:45 UTC
