### ISSUE TITLE
MoreThanOneSemesterWithOpenRecordsException

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#858] opened 2020-02-27 16:26 UTC
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/308/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/308/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1582811123/zapisy/apps/users/views.py", line 341, in create_ical_file
    semester = Semester.get_default_semester()
  File "/home/zapisy/projektzapisy/releases/1582811123/zapisy/apps/enrollment/courses/models/semester.py", line 301, in get_default_semester
    raise MoreThanOneSemesterWithOpenRecordsException()
MoreThanOneSemesterWithOpenRecordsException
```

**Comment by jasiekmarc** [comment] 2020-03-03 15:52
Duplicate of #824.

**Closed by jasiekmarc** 2020-03-03 15:52 UTC
Labels: duplicate
