### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'description'

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#677] opened 2019-05-04 15:17 UTC
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/256/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/256/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/projektzapisy/releases/1556541473/zapisy/apps/enrollment/courses/views.py", line 138, in course_ajax
    rendered_html = render_to_string('courses/course_info.html', data, request)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/api/function_trace.py", line 98, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/api/function_trace.py", line 98, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/defaulttags.py", line 302, in render
    match = condition.eval(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/defaulttags.py", line 875, in eval
    return self.value.resolve(context, ignore_failures=True)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/zapisy/projektzapisy/releases/1556541473/zapisy/apps/enrollment/courses/models/course.py", line 552, in description
    return self.information.description
AttributeError: 'NoneType' object has no attribute 'description'Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'Course' object is not subscriptable
```

**Comment by jasiekmarc** [comment] 2019-05-04 18:44
Duplicate of #673.

**Closed by jasiekmarc** 2019-05-04 18:44 UTC
